// File contains types representing the Zanzibar's Permission Tuple data model.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/model/tuples.proto

package model

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserType represents the variant in how the User type should be interpreted.
//
// The data model allows for an user to be an intermidiary node or
// a Leaf which represents an object.
// The Leaf Nodes of the Graph should - under normal usage - represent
// client application specific subjects (ie entities which needs to be authorized).
type NodeType int32

const (
	NodeType_ACTOR     NodeType = 0 // Represents an Application Actor / User - usually leaves
	NodeType_ATTRIBUTE NodeType = 1 // Represents a leave that is used to store data relating to a Relation
	NodeType_RELATION  NodeType = 2 // Represents a Relation Node, which defines an object / relation pair
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "ACTOR",
		1: "ATTRIBUTE",
		2: "RELATION",
	}
	NodeType_value = map[string]int32{
		"ACTOR":     0,
		"ATTRIBUTE": 1,
		"RELATION":  2,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_model_tuples_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_proto_model_tuples_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_proto_model_tuples_proto_rawDescGZIP(), []int{0}
}

type AuthNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      NodeType `protobuf:"varint,1,opt,name=type,proto3,enum=model.NodeType" json:"type,omitempty"`
	Namespace string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ObjectId  string   `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	Relation  string   `protobuf:"bytes,4,opt,name=relation,proto3" json:"relation,omitempty"`
}

func (x *AuthNode) Reset() {
	*x = AuthNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_model_tuples_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthNode) ProtoMessage() {}

func (x *AuthNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_model_tuples_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthNode.ProtoReflect.Descriptor instead.
func (*AuthNode) Descriptor() ([]byte, []int) {
	return file_proto_model_tuples_proto_rawDescGZIP(), []int{0}
}

func (x *AuthNode) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_ACTOR
}

func (x *AuthNode) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AuthNode) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *AuthNode) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

var File_proto_model_tuples_proto protoreflect.FileDescriptor

var file_proto_model_tuples_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x74, 0x75,
	0x70, 0x6c, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x22, 0x86, 0x01, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x23,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2a, 0x32, 0x0a, 0x08, 0x4e, 0x6f,
	0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x54, 0x54, 0x52, 0x49, 0x42, 0x55, 0x54, 0x45, 0x10, 0x01,
	0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x30,
	0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2d, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x62, 0x61, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_model_tuples_proto_rawDescOnce sync.Once
	file_proto_model_tuples_proto_rawDescData = file_proto_model_tuples_proto_rawDesc
)

func file_proto_model_tuples_proto_rawDescGZIP() []byte {
	file_proto_model_tuples_proto_rawDescOnce.Do(func() {
		file_proto_model_tuples_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_model_tuples_proto_rawDescData)
	})
	return file_proto_model_tuples_proto_rawDescData
}

var file_proto_model_tuples_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_model_tuples_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_model_tuples_proto_goTypes = []interface{}{
	(NodeType)(0),    // 0: model.NodeType
	(*AuthNode)(nil), // 1: model.AuthNode
}
var file_proto_model_tuples_proto_depIdxs = []int32{
	0, // 0: model.AuthNode.type:type_name -> model.NodeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_model_tuples_proto_init() }
func file_proto_model_tuples_proto_init() {
	if File_proto_model_tuples_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_model_tuples_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_model_tuples_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_model_tuples_proto_goTypes,
		DependencyIndexes: file_proto_model_tuples_proto_depIdxs,
		EnumInfos:         file_proto_model_tuples_proto_enumTypes,
		MessageInfos:      file_proto_model_tuples_proto_msgTypes,
	}.Build()
	File_proto_model_tuples_proto = out.File
	file_proto_model_tuples_proto_rawDesc = nil
	file_proto_model_tuples_proto_goTypes = nil
	file_proto_model_tuples_proto_depIdxs = nil
}
