// Code generated by protoc-gen-cobra. DO NOT EDIT.

package api

import (
	client "github.com/NathanBaulch/protoc-gen-cobra/client"
	flag "github.com/NathanBaulch/protoc-gen-cobra/flag"
	iocodec "github.com/NathanBaulch/protoc-gen-cobra/iocodec"
	domain "github.com/sourcenetwork/zanzi/pkg/domain"
	cobra "github.com/spf13/cobra"
	grpc "google.golang.org/grpc"
	proto "google.golang.org/protobuf/proto"
)

func RelationGraphClientCommand(options ...client.Option) *cobra.Command {
	cfg := client.NewConfig(options...)
	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("RelationGraph"),
		Short: "RelationGraph service client",
		Long:  "RelationGraph exposes lookup operations over a Policy's Relation Graph",
	}
	cfg.BindFlags(cmd.PersistentFlags())
	cmd.AddCommand(
		_RelationGraphCheckCommand(cfg),
		_RelationGraphExplainCheckCommand(cfg),
		_RelationGraphDOTExplainCheckCommand(cfg),
		_RelationGraphDumpRelationshipsCommand(cfg),
	)
	return cmd
}

func _RelationGraphCheckCommand(cfg *client.Config) *cobra.Command {
	req := &CheckRequest{
		AccessRequest: &domain.AccessRequest{
			Object:  &domain.Entity{},
			Subject: &domain.Entity{},
		},
	}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("Check"),
		Short: "Check RPC client",
		Long:  "Check verifies whether some subject has some relation to an object.\n Effectively this means a Graph Walk through the Relation Graph.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph", "Check"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewRelationGraphClient(cc)
				v := &CheckRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.Check(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.PolicyId, cfg.FlagNamer("PolicyId"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Resource, cfg.FlagNamer("AccessRequest Object Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Id, cfg.FlagNamer("AccessRequest Object Id"), "", "id is an unique identifier for the entity within a resource")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Relation, cfg.FlagNamer("AccessRequest Relation"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Resource, cfg.FlagNamer("AccessRequest Subject Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Id, cfg.FlagNamer("AccessRequest Subject Id"), "", "id is an unique identifier for the entity within a resource")

	return cmd
}

func _RelationGraphExplainCheckCommand(cfg *client.Config) *cobra.Command {
	req := &ExplainCheckRequest{
		AccessRequest: &domain.AccessRequest{
			Object:  &domain.Entity{},
			Subject: &domain.Entity{},
		},
	}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("ExplainCheck"),
		Short: "ExplainCheck RPC client",
		Long:  "ExplainCheck performs a Check call but outputs a simplified version\n of the internal goal tree.\n The goal tree can be used to understand the internals of the RelationGraph search and to debug.\n Note that the output of Explain Check IS NOT stable and it must be used for debug only.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph", "ExplainCheck"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewRelationGraphClient(cc)
				v := &ExplainCheckRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.ExplainCheck(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.PolicyId, cfg.FlagNamer("PolicyId"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Resource, cfg.FlagNamer("AccessRequest Object Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Id, cfg.FlagNamer("AccessRequest Object Id"), "", "id is an unique identifier for the entity within a resource")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Relation, cfg.FlagNamer("AccessRequest Relation"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Resource, cfg.FlagNamer("AccessRequest Subject Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Id, cfg.FlagNamer("AccessRequest Subject Id"), "", "id is an unique identifier for the entity within a resource")

	return cmd
}

func _RelationGraphDOTExplainCheckCommand(cfg *client.Config) *cobra.Command {
	req := &DOTExplainCheckRequest{
		AccessRequest: &domain.AccessRequest{
			Object:  &domain.Entity{},
			Subject: &domain.Entity{},
		},
	}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("DOTExplainCheck"),
		Short: "DOTExplainCheck RPC client",
		Long:  "ExplainCheck performs a Check call but outputs a DOT serialized version of the goal tree.\n Like ExplainCheck but outputs a DOT string",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph", "DOTExplainCheck"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewRelationGraphClient(cc)
				v := &DOTExplainCheckRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.DOTExplainCheck(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.PolicyId, cfg.FlagNamer("PolicyId"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Resource, cfg.FlagNamer("AccessRequest Object Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Object.Id, cfg.FlagNamer("AccessRequest Object Id"), "", "id is an unique identifier for the entity within a resource")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Relation, cfg.FlagNamer("AccessRequest Relation"), "", "")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Resource, cfg.FlagNamer("AccessRequest Subject Resource"), "", "resource represents the resource name which will contain the entity")
	cmd.PersistentFlags().StringVar(&req.AccessRequest.Subject.Id, cfg.FlagNamer("AccessRequest Subject Id"), "", "id is an unique identifier for the entity within a resource")
	cmd.PersistentFlags().BoolVar(&req.OmitUnknown, cfg.FlagNamer("OmitUnknown"), false, "")

	return cmd
}

func _RelationGraphDumpRelationshipsCommand(cfg *client.Config) *cobra.Command {
	req := &DumpRelationshipsRequest{}

	cmd := &cobra.Command{
		Use:   cfg.CommandNamer("DumpRelationships"),
		Short: "DumpRelationships RPC client",
		Long:  "DumpRelationships walks over a Policy's Relation Graph and returns \n a tree representaion of the Relationships set within a policy. \n Note that it *does not* perform evaluates relation rewrite rule,\n meaning that only explicit Relationship Tuples are dumped.",
		RunE: func(cmd *cobra.Command, args []string) error {
			if cfg.UseEnvVars {
				if err := flag.SetFlagsFromEnv(cmd.Parent().PersistentFlags(), true, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph"); err != nil {
					return err
				}
				if err := flag.SetFlagsFromEnv(cmd.PersistentFlags(), false, cfg.EnvVarNamer, cfg.EnvVarPrefix, "RelationGraph", "DumpRelationships"); err != nil {
					return err
				}
			}
			return client.RoundTrip(cmd.Context(), cfg, func(cc grpc.ClientConnInterface, in iocodec.Decoder, out iocodec.Encoder) error {
				cli := NewRelationGraphClient(cc)
				v := &DumpRelationshipsRequest{}

				if err := in(v); err != nil {
					return err
				}
				proto.Merge(v, req)

				res, err := cli.DumpRelationships(cmd.Context(), v)

				if err != nil {
					return err
				}

				return out(res)

			})
		},
	}

	cmd.PersistentFlags().StringVar(&req.PolicyId, cfg.FlagNamer("PolicyId"), "", "")
	flag.EnumVar(cmd.PersistentFlags(), &req.Format, cfg.FlagNamer("Format"), "")

	return cmd
}
