// File contains types representing the Zanzibar's Permission Tuple data model.
// The tuple data structure is used to persist the relation tuples in the datastore

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: internal/domain/tuples/tuple_record.proto

package tuple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelType indicate the type of relation defined by the tuple
type RelType int32

const (
	// Defines a relation from an object to a userset
	RelType_DELEGATION RelType = 0
	// Grant a relation to some actor
	RelType_GRANT RelType = 1
	// Defines a relation between two objects (non actor target)
	RelType_OBJECT_REL RelType = 2
)

// Enum value maps for RelType.
var (
	RelType_name = map[int32]string{
		0: "DELEGATION",
		1: "GRANT",
		2: "OBJECT_REL",
	}
	RelType_value = map[string]int32{
		"DELEGATION": 0,
		"GRANT":      1,
		"OBJECT_REL": 2,
	}
)

func (x RelType) Enum() *RelType {
	p := new(RelType)
	*p = x
	return p
}

func (x RelType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_domain_tuples_tuple_record_proto_enumTypes[0].Descriptor()
}

func (RelType) Type() protoreflect.EnumType {
	return &file_internal_domain_tuples_tuple_record_proto_enumTypes[0]
}

func (x RelType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelType.Descriptor instead.
func (RelType) EnumDescriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{0}
}

// ObjRel represents a `Userser` in Zanzibar terminology.
// It represents a Node in Zanzibar's relation graph.
type ObjRelRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Relation  string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
}

func (x *ObjRelRecord) Reset() {
	*x = ObjRelRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjRelRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjRelRecord) ProtoMessage() {}

func (x *ObjRelRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjRelRecord.ProtoReflect.Descriptor instead.
func (*ObjRelRecord) Descriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{0}
}

func (x *ObjRelRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjRelRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjRelRecord) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

// TupleRecord represents a Zanzibar Tuple that gets persisted
type TupleRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Object and relation relation information
	ObjectRel *ObjRelRecord `protobuf:"bytes,1,opt,name=object_rel,json=objectRel,proto3" json:"object_rel,omitempty"`
	// Actor, object or actor group node
	Actor *ObjRelRecord `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Type  RelType       `protobuf:"varint,3,opt,name=type,proto3,enum=internal.domain.tuple.RelType" json:"type,omitempty"`
	// Satellite data users can optionally embed within a tuple
	ClientData *anypb.Any `protobuf:"bytes,4,opt,name=client_data,json=clientData,proto3,oneof" json:"client_data,omitempty"`
}

func (x *TupleRecord) Reset() {
	*x = TupleRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TupleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleRecord) ProtoMessage() {}

func (x *TupleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleRecord.ProtoReflect.Descriptor instead.
func (*TupleRecord) Descriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{1}
}

func (x *TupleRecord) GetObjectRel() *ObjRelRecord {
	if x != nil {
		return x.ObjectRel
	}
	return nil
}

func (x *TupleRecord) GetActor() *ObjRelRecord {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *TupleRecord) GetType() RelType {
	if x != nil {
		return x.Type
	}
	return RelType_DELEGATION
}

func (x *TupleRecord) GetClientData() *anypb.Any {
	if x != nil {
		return x.ClientData
	}
	return nil
}

var File_internal_domain_tuples_tuple_record_proto protoreflect.FileDescriptor

var file_internal_domain_tuples_tuple_record_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70,
	0x6c, 0x65, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a,
	0x0c, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x02, 0x0a, 0x0b, 0x54, 0x75, 0x70, 0x6c,
	0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x42, 0x0a, 0x0a, 0x6f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x5f, 0x72, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75,
	0x70, 0x6c, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x52, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x12, 0x39, 0x0a, 0x05, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70,
	0x6c, 0x65, 0x2e, 0x4f, 0x62, 0x6a, 0x52, 0x65, 0x6c, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x32, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e,
	0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x6c,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x34, 0x0a, 0x07, 0x52, 0x65, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x45, 0x4c, 0x45, 0x47, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a,
	0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x45, 0x4c, 0x10, 0x02, 0x42, 0x40, 0x5a, 0x3e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2d,
	0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x62, 0x61, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_domain_tuples_tuple_record_proto_rawDescOnce sync.Once
	file_internal_domain_tuples_tuple_record_proto_rawDescData = file_internal_domain_tuples_tuple_record_proto_rawDesc
)

func file_internal_domain_tuples_tuple_record_proto_rawDescGZIP() []byte {
	file_internal_domain_tuples_tuple_record_proto_rawDescOnce.Do(func() {
		file_internal_domain_tuples_tuple_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_domain_tuples_tuple_record_proto_rawDescData)
	})
	return file_internal_domain_tuples_tuple_record_proto_rawDescData
}

var file_internal_domain_tuples_tuple_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_domain_tuples_tuple_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_domain_tuples_tuple_record_proto_goTypes = []interface{}{
	(RelType)(0),         // 0: internal.domain.tuple.RelType
	(*ObjRelRecord)(nil), // 1: internal.domain.tuple.ObjRelRecord
	(*TupleRecord)(nil),  // 2: internal.domain.tuple.TupleRecord
	(*anypb.Any)(nil),    // 3: google.protobuf.Any
}
var file_internal_domain_tuples_tuple_record_proto_depIdxs = []int32{
	1, // 0: internal.domain.tuple.TupleRecord.object_rel:type_name -> internal.domain.tuple.ObjRelRecord
	1, // 1: internal.domain.tuple.TupleRecord.actor:type_name -> internal.domain.tuple.ObjRelRecord
	0, // 2: internal.domain.tuple.TupleRecord.type:type_name -> internal.domain.tuple.RelType
	3, // 3: internal.domain.tuple.TupleRecord.client_data:type_name -> google.protobuf.Any
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_domain_tuples_tuple_record_proto_init() }
func file_internal_domain_tuples_tuple_record_proto_init() {
	if File_internal_domain_tuples_tuple_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_domain_tuples_tuple_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjRelRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_domain_tuples_tuple_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TupleRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_internal_domain_tuples_tuple_record_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_domain_tuples_tuple_record_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_domain_tuples_tuple_record_proto_goTypes,
		DependencyIndexes: file_internal_domain_tuples_tuple_record_proto_depIdxs,
		EnumInfos:         file_internal_domain_tuples_tuple_record_proto_enumTypes,
		MessageInfos:      file_internal_domain_tuples_tuple_record_proto_msgTypes,
	}.Build()
	File_internal_domain_tuples_tuple_record_proto = out.File
	file_internal_domain_tuples_tuple_record_proto_rawDesc = nil
	file_internal_domain_tuples_tuple_record_proto_goTypes = nil
	file_internal_domain_tuples_tuple_record_proto_depIdxs = nil
}
