// File contains types representing the Zanzibar's Permission Tuple data model.
// The tuple data structure is used to persist the relation tuples in the datastore

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: internal/domain/tuples/tuple_record.proto

package tuple

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeType indicates the type of information stored by the node
type NodeType int32

const (
	// Stores an Application Actor
	NodeType_ACTOR NodeType = 0
	// Stores a system object
	NodeType_OBJECT NodeType = 1
	// Stores a source of relation from one node to another
	// Recursively following a RELATION_SOURCE node lead to a set of actors / objects
	NodeType_RELATION_SOURCE NodeType = 2
	// Flags that node refers to all actors in the given namespace.
	// Used as a system constant to specify all known actors.
	NodeType_ALL_ACTORS NodeType = 4
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "ACTOR",
		1: "OBJECT",
		2: "RELATION_SOURCE",
		4: "ALL_ACTORS",
	}
	NodeType_value = map[string]int32{
		"ACTOR":           0,
		"OBJECT":          1,
		"RELATION_SOURCE": 2,
		"ALL_ACTORS":      4,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_domain_tuples_tuple_record_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_internal_domain_tuples_tuple_record_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{0}
}

// TupleNodeRecord represents a `Userset` in Zanzibar terminology.
// It represents a Node in Zanzibar's relation graph.
type TupleNodeRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Relation  string   `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	Type      NodeType `protobuf:"varint,4,opt,name=type,proto3,enum=internal.domain.tuple.NodeType" json:"type,omitempty"`
}

func (x *TupleNodeRecord) Reset() {
	*x = TupleNodeRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TupleNodeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleNodeRecord) ProtoMessage() {}

func (x *TupleNodeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleNodeRecord.ProtoReflect.Descriptor instead.
func (*TupleNodeRecord) Descriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{0}
}

func (x *TupleNodeRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TupleNodeRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TupleNodeRecord) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *TupleNodeRecord) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_ACTOR
}

// TupleRecord represents a Zanzibar Relation Tuple.
// A Relation Tuple defines a statment which relates
// system objects
type TupleRecord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *TupleNodeRecord `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest   *TupleNodeRecord `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	// partition_key is used to create logical partitions over tuples
	PartitionKey string `protobuf:"bytes,3,opt,name=partition_key,json=partitionKey,proto3" json:"partition_key,omitempty"`
}

func (x *TupleRecord) Reset() {
	*x = TupleRecord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TupleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleRecord) ProtoMessage() {}

func (x *TupleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_internal_domain_tuples_tuple_record_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleRecord.ProtoReflect.Descriptor instead.
func (*TupleRecord) Descriptor() ([]byte, []int) {
	return file_internal_domain_tuples_tuple_record_proto_rawDescGZIP(), []int{1}
}

func (x *TupleRecord) GetSource() *TupleNodeRecord {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *TupleRecord) GetDest() *TupleNodeRecord {
	if x != nil {
		return x.Dest
	}
	return nil
}

func (x *TupleRecord) GetPartitionKey() string {
	if x != nil {
		return x.PartitionKey
	}
	return ""
}

var File_internal_domain_tuples_tuple_record_proto protoreflect.FileDescriptor

var file_internal_domain_tuples_tuple_record_proto_rawDesc = []byte{
	0x0a, 0x29, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x5f, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70,
	0x6c, 0x65, 0x22, 0x90, 0x01, 0x0a, 0x0f, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0xae, 0x01, 0x0a, 0x0b, 0x54, 0x75, 0x70, 0x6c, 0x65, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x3e, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x2e, 0x54, 0x75,
	0x70, 0x6c, 0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x64,
	0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x74, 0x75, 0x70, 0x6c, 0x65, 0x2e, 0x54, 0x75, 0x70, 0x6c,
	0x65, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x64, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x4b, 0x65, 0x79, 0x2a, 0x46, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x45, 0x4c,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x02, 0x12, 0x0e,
	0x0a, 0x0a, 0x41, 0x4c, 0x4c, 0x5f, 0x41, 0x43, 0x54, 0x4f, 0x52, 0x53, 0x10, 0x04, 0x42, 0x40,
	0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2d, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x62, 0x61, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2f, 0x74, 0x75, 0x70, 0x6c, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_domain_tuples_tuple_record_proto_rawDescOnce sync.Once
	file_internal_domain_tuples_tuple_record_proto_rawDescData = file_internal_domain_tuples_tuple_record_proto_rawDesc
)

func file_internal_domain_tuples_tuple_record_proto_rawDescGZIP() []byte {
	file_internal_domain_tuples_tuple_record_proto_rawDescOnce.Do(func() {
		file_internal_domain_tuples_tuple_record_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_domain_tuples_tuple_record_proto_rawDescData)
	})
	return file_internal_domain_tuples_tuple_record_proto_rawDescData
}

var file_internal_domain_tuples_tuple_record_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_domain_tuples_tuple_record_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_domain_tuples_tuple_record_proto_goTypes = []interface{}{
	(NodeType)(0),           // 0: internal.domain.tuple.NodeType
	(*TupleNodeRecord)(nil), // 1: internal.domain.tuple.TupleNodeRecord
	(*TupleRecord)(nil),     // 2: internal.domain.tuple.TupleRecord
}
var file_internal_domain_tuples_tuple_record_proto_depIdxs = []int32{
	0, // 0: internal.domain.tuple.TupleNodeRecord.type:type_name -> internal.domain.tuple.NodeType
	1, // 1: internal.domain.tuple.TupleRecord.source:type_name -> internal.domain.tuple.TupleNodeRecord
	1, // 2: internal.domain.tuple.TupleRecord.dest:type_name -> internal.domain.tuple.TupleNodeRecord
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_domain_tuples_tuple_record_proto_init() }
func file_internal_domain_tuples_tuple_record_proto_init() {
	if File_internal_domain_tuples_tuple_record_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_domain_tuples_tuple_record_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TupleNodeRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_domain_tuples_tuple_record_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TupleRecord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_domain_tuples_tuple_record_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_domain_tuples_tuple_record_proto_goTypes,
		DependencyIndexes: file_internal_domain_tuples_tuple_record_proto_depIdxs,
		EnumInfos:         file_internal_domain_tuples_tuple_record_proto_enumTypes,
		MessageInfos:      file_internal_domain_tuples_tuple_record_proto_msgTypes,
	}.Build()
	File_internal_domain_tuples_tuple_record_proto = out.File
	file_internal_domain_tuples_tuple_record_proto_rawDesc = nil
	file_internal_domain_tuples_tuple_record_proto_goTypes = nil
	file_internal_domain_tuples_tuple_record_proto_depIdxs = nil
}
