// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: zanzi/types/check_explain_tree.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ExplainTree models the resulting goal tree from
// a Check execution
type CheckExplainTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string              `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Detail  string              `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Ok      []*CheckExplainTree `protobuf:"bytes,3,rep,name=ok,proto3" json:"ok,omitempty"`
	Failed  []*CheckExplainTree `protobuf:"bytes,4,rep,name=failed,proto3" json:"failed,omitempty"`
	Unknown []*CheckExplainTree `protobuf:"bytes,5,rep,name=unknown,proto3" json:"unknown,omitempty"`
}

func (x *CheckExplainTree) Reset() {
	*x = CheckExplainTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_zanzi_types_check_explain_tree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckExplainTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckExplainTree) ProtoMessage() {}

func (x *CheckExplainTree) ProtoReflect() protoreflect.Message {
	mi := &file_zanzi_types_check_explain_tree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckExplainTree.ProtoReflect.Descriptor instead.
func (*CheckExplainTree) Descriptor() ([]byte, []int) {
	return file_zanzi_types_check_explain_tree_proto_rawDescGZIP(), []int{0}
}

func (x *CheckExplainTree) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CheckExplainTree) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CheckExplainTree) GetOk() []*CheckExplainTree {
	if x != nil {
		return x.Ok
	}
	return nil
}

func (x *CheckExplainTree) GetFailed() []*CheckExplainTree {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *CheckExplainTree) GetUnknown() []*CheckExplainTree {
	if x != nil {
		return x.Unknown
	}
	return nil
}

var File_zanzi_types_check_explain_tree_proto protoreflect.FileDescriptor

var file_zanzi_types_check_explain_tree_proto_rawDesc = []byte{
	0x0a, 0x24, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x5f, 0x65, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x72, 0x65, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x87, 0x02, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x6c, 0x61,
	0x69, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x12, 0x3b, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b,
	0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x7a,
	0x61, 0x6e, 0x7a, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x02, 0x6f, 0x6b, 0x12,
	0x43, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2b, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e,
	0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x72, 0x65, 0x65, 0x52, 0x06, 0x66, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x6e, 0x65,
	0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x78, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x54, 0x72,
	0x65, 0x65, 0x52, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x42, 0x2a, 0x5a, 0x28, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_zanzi_types_check_explain_tree_proto_rawDescOnce sync.Once
	file_zanzi_types_check_explain_tree_proto_rawDescData = file_zanzi_types_check_explain_tree_proto_rawDesc
)

func file_zanzi_types_check_explain_tree_proto_rawDescGZIP() []byte {
	file_zanzi_types_check_explain_tree_proto_rawDescOnce.Do(func() {
		file_zanzi_types_check_explain_tree_proto_rawDescData = protoimpl.X.CompressGZIP(file_zanzi_types_check_explain_tree_proto_rawDescData)
	})
	return file_zanzi_types_check_explain_tree_proto_rawDescData
}

var file_zanzi_types_check_explain_tree_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_zanzi_types_check_explain_tree_proto_goTypes = []interface{}{
	(*CheckExplainTree)(nil), // 0: sourcenetwork.zanzi.types.CheckExplainTree
}
var file_zanzi_types_check_explain_tree_proto_depIdxs = []int32{
	0, // 0: sourcenetwork.zanzi.types.CheckExplainTree.ok:type_name -> sourcenetwork.zanzi.types.CheckExplainTree
	0, // 1: sourcenetwork.zanzi.types.CheckExplainTree.failed:type_name -> sourcenetwork.zanzi.types.CheckExplainTree
	0, // 2: sourcenetwork.zanzi.types.CheckExplainTree.unknown:type_name -> sourcenetwork.zanzi.types.CheckExplainTree
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_zanzi_types_check_explain_tree_proto_init() }
func file_zanzi_types_check_explain_tree_proto_init() {
	if File_zanzi_types_check_explain_tree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_zanzi_types_check_explain_tree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckExplainTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_zanzi_types_check_explain_tree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_zanzi_types_check_explain_tree_proto_goTypes,
		DependencyIndexes: file_zanzi_types_check_explain_tree_proto_depIdxs,
		MessageInfos:      file_zanzi_types_check_explain_tree_proto_msgTypes,
	}.Build()
	File_zanzi_types_check_explain_tree_proto = out.File
	file_zanzi_types_check_explain_tree_proto_rawDesc = nil
	file_zanzi_types_check_explain_tree_proto_goTypes = nil
	file_zanzi_types_check_explain_tree_proto_depIdxs = nil
}
