// Public Relations definitions

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: lib/relations.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationType int32

const (
	// Represents a relation from an ACTORSET to an OBJECT node.
	// used to express some relation between the source object and target object.
	RelationType_OBJECT_RELATION RelationType = 0
	// Represents an authorization grant between an ACTORSET and an ACTOR node
	// Effectively sets a relation between source object and dest actor
	RelationType_GRANT RelationType = 1
	// Represents a delegated relation between two ACTORSET nodes.
	// Delegation is used to build indirect relations between users
	RelationType_DELEGATION RelationType = 2
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "OBJECT_RELATION",
		1: "GRANT",
		2: "DELEGATION",
	}
	RelationType_value = map[string]int32{
		"OBJECT_RELATION": 0,
		"GRANT":           1,
		"DELEGATION":      2,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_lib_relations_proto_enumTypes[0].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_lib_relations_proto_enumTypes[0]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{0}
}

// Identifies a system entity
type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_relations_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_lib_relations_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{0}
}

func (x *Id) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Id) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Relate two generic system objects
type ObjectRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object   *Id    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject  *Id    `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *ObjectRelation) Reset() {
	*x = ObjectRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_relations_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectRelation) ProtoMessage() {}

func (x *ObjectRelation) ProtoReflect() protoreflect.Message {
	mi := &file_lib_relations_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectRelation.ProtoReflect.Descriptor instead.
func (*ObjectRelation) Descriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{1}
}

func (x *ObjectRelation) GetObject() *Id {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *ObjectRelation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ObjectRelation) GetSubject() *Id {
	if x != nil {
		return x.Subject
	}
	return nil
}

// Grant a relation to a system actor
type GrantRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object   *Id    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Actor    *Id    `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
}

func (x *GrantRelation) Reset() {
	*x = GrantRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_relations_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrantRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRelation) ProtoMessage() {}

func (x *GrantRelation) ProtoReflect() protoreflect.Message {
	mi := &file_lib_relations_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRelation.ProtoReflect.Descriptor instead.
func (*GrantRelation) Descriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{2}
}

func (x *GrantRelation) GetObject() *Id {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GrantRelation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GrantRelation) GetActor() *Id {
	if x != nil {
		return x.Actor
	}
	return nil
}

// Delegate `relation` from `object` to any actor
// reachable reachable from `subject` through `subject_relation`.
type DelegationRelation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Object          *Id    `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	Relation        string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	Subject         *Id    `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectRelation string `protobuf:"bytes,4,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
}

func (x *DelegationRelation) Reset() {
	*x = DelegationRelation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_relations_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelegationRelation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelegationRelation) ProtoMessage() {}

func (x *DelegationRelation) ProtoReflect() protoreflect.Message {
	mi := &file_lib_relations_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelegationRelation.ProtoReflect.Descriptor instead.
func (*DelegationRelation) Descriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{3}
}

func (x *DelegationRelation) GetObject() *Id {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *DelegationRelation) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *DelegationRelation) GetSubject() *Id {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *DelegationRelation) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *anypb.Any `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lib_relations_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_lib_relations_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_lib_relations_proto_rawDescGZIP(), []int{4}
}

func (x *UserData) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_lib_relations_proto protoreflect.FileDescriptor

var file_lib_relations_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x69, 0x62, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6c, 0x69, 0x62, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x0e, 0x4f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x06, 0x6f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6c, 0x69,
	0x62, 0x2e, 0x49, 0x64, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6c, 0x69, 0x62, 0x2e,
	0x49, 0x64, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x6b, 0x0a, 0x0d, 0x47,
	0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x06,
	0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6c,
	0x69, 0x62, 0x2e, 0x49, 0x64, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x05, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x6c, 0x69, 0x62, 0x2e, 0x49,
	0x64, 0x52, 0x05, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x9f, 0x01, 0x0a, 0x12, 0x44, 0x65, 0x6c,
	0x65, 0x67, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1f, 0x0a, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x07, 0x2e, 0x6c, 0x69, 0x62, 0x2e, 0x49, 0x64, 0x52, 0x06, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x07,
	0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e,
	0x6c, 0x69, 0x62, 0x2e, 0x49, 0x64, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12,
	0x29, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x75, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x3e,
	0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13,
	0x0a, 0x0f, 0x4f, 0x42, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x52, 0x45, 0x4c, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x47, 0x52, 0x41, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0e,
	0x0a, 0x0a, 0x44, 0x45, 0x4c, 0x45, 0x47, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2d, 0x7a, 0x61, 0x6e, 0x7a, 0x69, 0x62, 0x61, 0x72, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lib_relations_proto_rawDescOnce sync.Once
	file_lib_relations_proto_rawDescData = file_lib_relations_proto_rawDesc
)

func file_lib_relations_proto_rawDescGZIP() []byte {
	file_lib_relations_proto_rawDescOnce.Do(func() {
		file_lib_relations_proto_rawDescData = protoimpl.X.CompressGZIP(file_lib_relations_proto_rawDescData)
	})
	return file_lib_relations_proto_rawDescData
}

var file_lib_relations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lib_relations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_lib_relations_proto_goTypes = []interface{}{
	(RelationType)(0),          // 0: lib.RelationType
	(*Id)(nil),                 // 1: lib.Id
	(*ObjectRelation)(nil),     // 2: lib.ObjectRelation
	(*GrantRelation)(nil),      // 3: lib.GrantRelation
	(*DelegationRelation)(nil), // 4: lib.DelegationRelation
	(*UserData)(nil),           // 5: lib.UserData
	(*anypb.Any)(nil),          // 6: google.protobuf.Any
}
var file_lib_relations_proto_depIdxs = []int32{
	1, // 0: lib.ObjectRelation.object:type_name -> lib.Id
	1, // 1: lib.ObjectRelation.subject:type_name -> lib.Id
	1, // 2: lib.GrantRelation.object:type_name -> lib.Id
	1, // 3: lib.GrantRelation.actor:type_name -> lib.Id
	1, // 4: lib.DelegationRelation.object:type_name -> lib.Id
	1, // 5: lib.DelegationRelation.subject:type_name -> lib.Id
	6, // 6: lib.UserData.data:type_name -> google.protobuf.Any
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_lib_relations_proto_init() }
func file_lib_relations_proto_init() {
	if File_lib_relations_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lib_relations_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_relations_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_relations_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrantRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_relations_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelegationRelation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lib_relations_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_lib_relations_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lib_relations_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_lib_relations_proto_goTypes,
		DependencyIndexes: file_lib_relations_proto_depIdxs,
		EnumInfos:         file_lib_relations_proto_enumTypes,
		MessageInfos:      file_lib_relations_proto_msgTypes,
	}.Build()
	File_lib_relations_proto = out.File
	file_lib_relations_proto_rawDesc = nil
	file_lib_relations_proto_goTypes = nil
	file_lib_relations_proto_depIdxs = nil
}
